### ISSUE TITLE
run and setup ewallet app

### ISSUE THREAD

**Issue by AnilFinstack** [trainingfinstack/Core-Java#11]

**Comment by dizayn3r** [comment]
Unable to connect with the API while posting. Check the parsing url along with header and body. Bearer token is correct. Working on implementation of api 

![Image](https://user-images.githubusercontent.com/64494203/187417997-a635e7e3-5cfb-4ffc-9464-9396aa426a0c.png)

.

**Comment by dizayn3r** [comment]
After using token generation by using post in postman it show connection close.

{
    "username": "wowfintech",
    "password": "wowfintech123",
    "tokenValidity": "24"
}

API Link: http://140.238.255.196:9595/token

**Comment by dizayn3r** [comment]
Error while calling API 

- API Link http://140.238.255.196:9002/eWallet/ewallet/v1.0/customerRegistration/
- Status Code 404.

![Screenshot 2022-08-31 111815](https://user-images.githubusercontent.com/64494203/187613556-927d49a6-6336-4bb8-8db9-275dd07ee7d5.png)

**Comment by dizayn3r** [comment]
Push code to separate branch in github along with pull request.

**Comment by dizayn3r** [comment]
Regenerate pull request after implementing the changes.

**Comment by dizayn3r** [comment]
After connecting with API few error arise 

1. Country field and Nationality field only accepting uppercase alpha letter corrected by using toUpperCase after **value!. Trim().toUpperCase**.
2. When trying to post details to API, these response arise **Response Code "117"** and **Response Text "Registration application is rejected"**.
3. Even after generating new user the response is same.
4. **Status Code "500"** which is internal server error.
5.  [API Link](http://140.238.255.196:9002/eWallet/ewallet/v1.0/customerRegistration/)

**Error Snippets:**
![Image](https://user-images.githubusercontent.com/64494203/188610685-f1a0e2e0-83b2-4ae9-ba5a-fb41a84c871f.png)
![Image](https://user-images.githubusercontent.com/64494203/188610684-f4e27436-1f74-4488-9104-132718188b9f.png)

**Comment by dizayn3r** [comment]
Fix mobile number issue in wallet dashboard as well as qr code issue.

**Comment by AnilFinstack** [comment]
@dizayn3r this task was only for setup related changes.
don't put any issues fix changes in this task.
