### ISSUE TITLE
Github understanding

### ISSUE THREAD

**Issue by AnilFinstack** [trainingfinstack/Core-Java#14]
[Git Tutorial](https://www.w3schools.com/git/)

[Git Tutorial for Beginners: Learn Git in 1 Hour](https://www.youtube.com/watch?v=8JJ101D3knE)

**Comment by Neyaj786** [comment]
What is Git/Github.
How to install Git/Gitbash.
How to check version.
How to initialize Git.
How to set/config user name.
How to config email.

**Comment by Neyaj786** [comment]
Pushing and Pulling code from Git.
Scanning changes to files using git different command.
Git add -A and Git add . difference.
Cloning a Git repository.
Ignoring files in Git by adding .gitignore file.
