### ISSUE TITLE
Application(Salayze) debugging

### ISSUE THREAD

**Issue by AnilFinstack** [trainingfinstack/Core-Java#19]
https://github.com/trainingfinstack/salayze

**Comment by AyushTiwari1126** [comment]
There are four parameters by which it conclude that the code define the Salayze(SQL analyzer Application).

1. Parse File :- 
ParseFile method takes file and FileReader firstly read file input & buffering input characters.
getName method returns the directory name by taking lastIndexOf(seperatorchar)

2. Generate SQL Statements  :- 
getPossibleSQLStrings method assign to String typed List
create vector name sqls and QueryParameter typed list 'qps' in which getQueryCalls method call and a QueryParameter typed List is created.
create QueryParameter object qp that can add into list and return list.
Now QueryParameters iterate into list 'qps' and QueryParameters call generateAllPossibleValues method that furthur call parseAllPossibleValues method
In this method, create a string type vector called possibleValues
if parameter type is equals to java token identifier then parseJavaFile method call
Here, the file is not null then it will call getPossibleValues method, in which the stack can hold SQL Queries then it can retrieve buffer string from stack and added to list, and it gives us all the SQL String statements into a list and return the list.
Now a string 's' can retrieve SQL String values from getAllPossibleValues method and add these statements are add into sqls list and returns this sqls list.


3. Parse SQL Queries :- A SQL string is taken by parseQuery method in which the replaceJavaVars method call with taking string query and create a string type Hashtable named var_lookup and check that the string query contains any int or string type character, then returns string query.
4. Validate Query :-

**Comment by AyushTiwari1126** [comment]
**There are mainly four parameters which simply conclude Salayze(SQL Analyzer Application) :-** 

**(1). Parse File :-** 
---> ParseFile method takes path of file and FileReader firstly read characters from input file & buffering input characters.
---> After that, getName method returns the name of the directory.



**(2). Generating SQL Queries :-** 
--->Starting with getPossibleSQLStrings method that define a list named 'sqls' and QueryParameter typed list 'qps' in which call getQueryCalls method and a QueryParameter typed List is defined. After ### that a QueryParameter object qp that can add into list and then return list.
--->Now QueryParameters iterate into list 'qps' and QueryParameter calls generateAllPossibleValues method that furthur call parseAllPossibleValues method. In this method, define a string type vector called possibleValues.
---> Now check that the parameter type is equals to java token identifier then call parseJavaFile method.
Here, the file is not null then it will call getPossibleValues method, in which the stack can hold SQL Queries then retrieve buffer string from stack and added to list, and gives us all the SQL String statements into a list and return the list.
--->Now a string 's' can retrieve SQL String values from getAllPossibleValues method and add these statements are add into sqls list and returns this sqls list.



**(3). Parse SQL Query :-** 
---> A SQL string is taken by parseQuery method in which the replaceJavaVars method call with taking string query and create a string type Hashtable named var_lookup and check that the string query contains any int or string type character, then returns string type queries.



**(4). Validate Query :-**
---> In validation, first validate tables, define a 'Tables' list then call tableExists method that takes tablename and check for the tables list contains any tablename and then return tablename.
--->Secondly,In the validation of columns, create Tables and columns list then retrieve tablename from 'TablesList' and Similarly, columnExists method check 'columns' List contains any columnName and returns column name.
Third validate Where Statement that checks the expression is null or not then create list called expressions that gets operands from it.

**Comment by AyushTiwari1126** [comment]
**There are four parameters which conclude the Salayze(SQL Analyzer Application)**

**(1). Parse File**
ParseFile method takes path of file and FileReader firstly read characters from input file & buffering input characters.
getName method returns the name of the directory.


**(2). Generating SQL Queries**
---> Starting with getPossibleSQLStrings method create a list named 'sqls' and QueryParameter typed list 'qps' in which getQueryCalls method calls and a QueryParameter typed List is defined. A QueryParameter object qp that can add into list and return list.
---> Now QueryParameters iterate into list 'qps' and QueryParameter calls generateAllPossibleValues method that furthur call parseAllPossibleValues method. In this method, define a string type vector called possibleValues. then check that the parameter type is equals to java token identifier then call parseJavaFile method.
---> Now, the file is not null then it will call getPossibleValues method, in which the stack can hold SQL Queries then it can retrieve buffer string from stack and added to list, and it gives us all the SQL String statements into a list and return the list.
---> Now a string 's' can retrieve SQL String values from getAllPossibleValues method and add these statements are add into sqls list and returns this sqls list.


**(3). Parse SQL Query :-** 
---> A SQL string is taken by parseQuery method in which the replaceJavaVars method call with taking string query and create a string type Hashtable named var_lookup and check that the string query contains any int or string type character, then returns string query.


**(4). Validate Query :-**
---> In validation, first validate tables => define a 'Tables' list then call tableExists method that takes tablename and check for the 'tables' list contains any tablename and then return tablename.
---> Secondly,In the validation of columns, create 'Tables' and 'columns' list then retrieve tablename from TablesList and Similarly, columnExists method check 'columns' List contains any column name and returns column name.
Third validate Where Statement that checks the expression is null or not then create list called expressions that gets operands from it.
