### ISSUE TITLE
debugging, spring boot, jdbc, SOLID

### ISSUE THREAD

**Issue by AnilFinstack** [trainingfinstack/Core-Java#25]
(1) Debugging 
In this task, following operation of debugging should be practice and proficiency should be achieved in these.

step in
step out
come out of the function
going inside library function
pause, stop, continue debugging
knowing local variable values
etc

   https://stackify.com/java-debugging-tips/#top-10-java-debugging-tips-5
(2) JDBC connection

(3) spring boot - https://youtube.com/playlist?list=PL0zysOflRCelmjxj-g4jLr3WKraSU_e8q
DAO/DTO   - https://stackoverflow.com/questions/14366001/dto-and-dao-concepts-and-mvc
restfull API
mybatis

(4) SOLID Principle and naming convention

**Comment by priya19g** [comment]
How to Debug a code in java: https://stackify.com/java-debugging-tips/#top-10-java-debugging-tips-5

Learn how to establish a JDBC Connection : https://www.youtube.com/results?search_query=code+with+durgesh+jdbc+connection+in+java

**Comment by priya19g** [comment]
JPA : https://www.youtube.com/watch?v=2IQsjvZoOkg&list=PL0zysOflRCelmjxj-g4jLr3WKraSU_e8q&index=21

 Postman : https://www.youtube.com/watch?v=2IQsjvZoOkg&list=PL0zysOflRCelmjxj-g4jLr3WKraSU_e8q&index=21

Spring Boot : https://www.youtube.com/watch?v=2IQsjvZoOkg&list=PL0zysOflRCelmjxj-g4jLr3WKraSU_e8q&index=21

HTTP Methods : GET
                          POST
                          PUT
                          DELETE

**Comment by priya19g** [comment]
Spring BOOT : CUSTOM FINDER METHOD 
                        SPRING BOOT USING JPA AND CRUD OPERATIONS

**Comment by priya19g** [comment]
SpringBoot : Learn DTO And DAO  

Learn : MyBatis 

Link : [Spring MVC and MyBatis/iBatis Database Tutorial - Introduction - #01 - YouTube](https://www.youtube.com/watch?v=-PcU6uf-p3g&list=PLA7e3zmT6XQUNzbNoTb-8c-VTa_i_w5-y)

Learn SOLID Principle and naming convention
